### ISSUE TITLE
BUG: Shared event (where I am a guest) is showing up a day early in my daily notes

### ISSUE THREAD

**Issue by dlhawe** [cloud-atlas-ai/obsidian-ics#98] opened 2024-01-04 17:07 UTC
I'm using the ICS plugin to pull events from my Google calendar into my daily notes.  I am having an issue where a shared event (where I am a guest) is showing up a day early in my daily notes, but calendar events I enter are showing up on the proper day.  There doesn't appear to be anything in the configuration settings to explain thus behavior.

**Comment by muness** [comment] 2024-01-04 17:12
Thanks for the bug report @dlhawe . Is there anything else you can add to help debug this? Maybe the ICS VEVENT entry, anonymized?

To do that, download the ICS file to an editor, and find the VEVENT entry, and copy/paste it in?

The parsing is entirely done through `node-ical` and `rrule` aside from timezone manipulation I do to try to coerce the events into the right timezones. So there's not a lot of logic for that would explain this issue from the ICS plugin itself.

**Comment by dlhawe** [comment] 2024-01-04 17:51
Thanks for your speedy reply.  Im not a frequent github user, would you prefer it pasted here or attached (if that is even possible)?  Also, I will post two vevents as I am not sure which is the one from the creator and which is mine if that is ok.

**Comment by muness** [comment] 2024-01-04 19:36
Thank you so much, I'll take a look and see if I have any ideas! Probably over the weekend.

Diagnosing this stuff is very hard when I don't have a VEVENT to reproduce the issue with.

**Comment by muness** [comment] 2024-01-04 19:37
Can you add @dlhawe , which events are coming through on the wrong day? i.e. which day did it show up in, when did you expect it? That'll help me when I try to reproduce the issue.

**Comment by dlhawe** [comment] 2024-01-04 20:08
So those two VEVENT items are two views of the same calendar event as my wife has shared her calendar with me.  One of the events is my wife's event (creator) on her calendar, the other is the same event on my calendar (guest).  Not sure which event is which above.

The event is scheduled for 17:00 today (2024-01-04) at 17:00 and shows up properly on my phone and calendar web page.  This event showed up on yesterdays (2024-01-03) daily note and did not show on today's daily note.

Please let me know if showing you the code I am using to pull the event on my daily calendar would be of use, I can post that as well.

Thanks for having a look, and no rush.  It's a mild annoyance and certainly not a deal breaker for a fantasic plugin.

**Comment by muness** [comment] 2024-01-04 21:33
@dlhawe I am confused but may see the issue
- these VEVENTS have different start dates:
- you declined one and accepted the other

```
DTSTART;TZID=America/Los_Angeles:20231019T170000
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=me
 @gmail.com;X-NUM-GUESTS=0:mailto:me@gmail.com
...
DTSTART;TZID=America/Los_Angeles:20231228T170000
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=DECLINED;CN=me
 @gmail.com;X-NUM-GUESTS=0:mailto:me@gmail.com
```

Because of #19 , this could explain the apparently erroneous entry yesterday.

That doesn't explain why it didn't show up today though.

**Comment by dlhawe** [comment] 2024-01-04 23:07
So I am a bit confused (and embarrassed).

Neither of these events are the event from today.  I just posted the last two entries from the reoccuring event.  I apologize for that.  Given that I wasnt importing calendar events on 20231019 (first VEVENT), I can't comment on that.  TBH, I didn;'t notice if the 20231228 event posted early, but I can confirm I did decline it.

The confusing part is that I don't have an entry in my ICAL dump for the 20240104 event that posted to yesterdays daily note, nor for any of the future reoccuring events in that series as far as I can tell which makes diagnosing this issue problematic.  I am also noticing that reoccuring future events I have personally posted dont show on the ICAL dump either.

The more I post about this, the dumber I sound.  Sorry.

**Comment by muness** [comment] 2024-01-04 23:22
Don't be embarrassed! Recurring rules are strange beasts and supremely counterintuitive.

You might be able to find the event by searching for the Google meet link. There should then be an rrule section below it, that's where the instances are declared and the client has to compute them.

**Comment by dlhawe** [comment] 2024-01-05 02:30
So I was able to get the desired event to export by switching my attendence from yes to maybe, then back to yes.  That seemed to update the event and allow it to export.  Reminder: This event was today (2024-01-04), and it a reoccuring event every Thurs at 5pm PST.  I am a guest on this reoccuring event.  This specific event imported a day early (2024-01-03) onto my daily note.

```
BEGIN:VEVENT
DTSTART;TZID=America/Los_Angeles:20240104T170000
DTEND;TZID=America/Los_Angeles:20240104T173000
DTSTAMP:20240105T021357Z
ORGANIZER;CN=creator@gmail.com:mailto:creator@gmail.com
UID:5258ABF7-D498-4F2E-9604-73009A40DE1A
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=guest
 @gmail.com;X-NUM-GUESTS=0:mailto:guest@gmail.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=creator
 @gmail.com;X-NUM-GUESTS=0:mailto:creator@gmail.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=son@gmail.com;X-NUM-GUESTS=0:mailto:yeetnugget234son@gmail.com
X-GOOGLE-CONFERENCE:https://meet.xxx
RECURRENCE-ID;TZID=America/Los_Angeles:20240104T170000
CLASS:PUBLIC
CREATED:20231013T185343Z
DESCRIPTION:-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~
 :~:~:~:~:~:~:~:~::~:~::-\nJoin with Google Meet: https://meet.google.com/xxx Learn more about Meet at: https://support.google.com/a/users/
 answer/9282720\n\nPlease do not edit this section.\n-::~:~::~:~:~:~:~:~:~:~
 :~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-
LAST-MODIFIED:20240105T021251Z
LOCATION:xxx, Tustin\, CA 927
 80\, USA
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:Son - swim
TRANSP:OPAQUE
END:VEVENT
```

**Comment by muness** [comment] 2024-01-11 00:36
Forgot to update this...

1. Added that as an ICS under a vdir I use for testing.
2. Did _not_ see it on 2023-01-03 and it shows up on 2023-01-04 for me.

```
- [ ] 20:00 - 20:30 test Son - swim [Google Meet](https://meet.xxx)
```

Surprisingly, it shows up _twice_.

**Comment by muness** [comment] 2024-01-11 00:39
With that, I am at a loss as to how to debug this further. I'll see if I can figure out why it's getting listed twice.

**Comment by muness** [comment] 2024-01-11 01:01
> Surprisingly, it shows up _twice_.

This was a separate issue, fixed in #100.

**Comment by dlhawe** [comment] 2024-01-11 06:03
Thank you for testing, I sincerely appreciate it.  It seems to me that it is either an issue with me being a guest on my wife's event and/or the fact it is is reoccuring event.  I have a reoccuring event that starts on Monday that I created, and I'll provide feedback if desired as to if that shows up properly.

**Comment by devangnegandhi** [comment] 2024-01-15 01:46
FYI - I am seeing a similar issue on my google calendar. Only on recurring events - both on shared calendar as well as a personal calendar.

**Comment by muness** [comment] 2024-01-15 01:52
> FYI - I am seeing a similar issue on my google calendar. Only on recurring events - both on shared calendar as well as a personal calendar.
> 
> A latest example is I have an event tomorrow evening, but it is showing up on my obsidian today when using this plugin

Thanks for the update. Can you share more details? I haven't been able to replicate this and since I leverage `node-ical` and `rrule` I don't know if I am introducing a bug or if it's something in them. The VEVENT is ideal along with details of what you're seeing would be ideal.

**Comment by devangnegandhi** [comment] 2024-01-15 02:00
I see this message in my obsidian developer console

`
Found a recurring event to clone:  <anonymized - this was a meeting name>  on  Sun Jan 14 2024 20:00:00 GMT-0800 (Pacific Standard Time) at  Mon Jan 08 2024 20:00:00 GMT-0800 (Pacific Standard Time)
`

RRULE origOptions: 
```javascript
{
    "tzid": "America/Los_Angeles",
    "dtstart": "2024-01-09T04:00:00.000Z",
    "freq": 2,
    "wkst": {
        "weekday": 6
    },
    "until": "2024-03-06T07:59:59.000Z",
    "byweekday": [
        {
            "weekday": 0
        }
    ]
}
```
`
Event rrule.origOptions.tzid: America/Los_Angeles
`
Cloned event: 
```javascript
{
    "type": "VEVENT",
    "params": [],
    "start": "Sun Jan 14 2024 20:00:00 GMT-0800 (Pacific Standard Time)",
    "datetype": "date-time",
    "end": "Sun Jan 14 2024 21:00:00 GMT-0800 (Pacific Standard Time)",
    "exdate": [],
    "dtstamp": "2024-01-15T01:48:11.000Z",
    "uid": "74tq9lsp6n0qlgln9lph6c3700@google.com",
    "created": "2024-01-08T22:47:14.000Z",
    "description": "<anonymized description>",
    "lastmodified": "2024-01-08T22:47:14.000Z",
    "sequence": "0",
    "status": "CONFIRMED",
    "summary": "<anonymized - this was a meeting name>",
    "transparency": "OPAQUE",
    "method": "PUBLISH"
}
```

**Comment by devangnegandhi** [comment] 2024-01-15 02:01
Also, I see this error show up ~460 times in the same console

`Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone`

not sure if that is relevant

**Comment by muness** [comment] 2024-01-15 02:12
Thanks! 
- What Calendar provider do you use?
- Is the event getting added to the wrong day? Or is it missing altogether?

**Comment by devangnegandhi** [comment] 2024-01-15 02:23
I use google calendar. And its showing it on the wrong day - specifically a day earlier. The event is supposed to be tomorrow evening, but this plugin is showing me that it is taking place today.

Here is the raw VEVENT event from .ics file
```
BEGIN:VEVENT
DTSTART;TZID=America/Los_Angeles:20240108T200000
DTEND;TZID=America/Los_Angeles:20240108T210000
RRULE:FREQ=WEEKLY;WKST=SU;UNTIL=20240306T075959Z;BYDAY=MO
EXDATE;TZID=America/Los_Angeles:20240115T200000
DTSTAMP:20240115T020925Z
UID:74tq9lsp6n0qlgln9lph6c3700@google.com
CREATED:20240108T224714Z
DESCRIPTION:<anonymized description>
LAST-MODIFIED:20240108T224714Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY: <anonymized - this was a meeting name>
TRANSP:OPAQUE
END:VEVENT
```

As you can see, FREQ=WEEKLY and WKST=SU and BYDAY=MO. The week should be starting on Sunday, and it should not be showing me this event tomorrow (monday). 

But the cloned event object (from my previous message [above](https://github.com/cloud-atlas-ai/obsidian-ics/issues/98#issuecomment-1891188281)) is suggesting my "wkst" is Saturday (6), and "byweekday" as Sunday (0).

Could that be the issue?

**Comment by muness** [comment] 2024-01-15 02:27
There might be an issue with `rrule` and its timezone parsing, per https://github.com/jkbrzt/rrule/issues/427 . Putting together a build that locks in to `rrule` version 2.6.4 per the comments on that issue.

**Comment by muness** [comment] 2024-01-15 02:28
@devangnegandhi - can you test with https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.6.1test ? Specifically replace `main.js` with the one on this release, restart obsidian and give it a try. 🙏

**Comment by devangnegandhi** [comment] 2024-01-15 02:46
All the massive # of console errors are no longer there. BUT unfortunately, the issue still persists. Here is an updated output in the console based on the new main.js file you provided

`RRULE origOptions`
```javascript
{
    "tzid": "America/Los_Angeles",
    "dtstart": "2024-01-09T04:00:00.000Z",
    "freq": 2,
    "wkst": {
        "weekday": 6
    },
    "until": "2024-03-06T07:59:59.000Z",
    "byweekday": [
        {
            "weekday": 0
        }
    ]
}
```

`Cloned event:`
```javascript
{
    "type": "VEVENT",
    "params": [],
    "start": "Sun Jan 14 2024 20:00:00 GMT-0800 (Pacific Standard Time)",
    "datetype": "date-time",
    "end": "Sun Jan 14 2024 21:00:00 GMT-0800 (Pacific Standard Time)",
    "exdate": [],
    "dtstamp": "2024-01-15T02:37:59.000Z",
    "uid": "74tq9lsp6n0qlgln9lph6c3700@google.com",
    "created": "2024-01-08T22:47:14.000Z",
    "description": "<anonymized description>",
    "lastmodified": "2024-01-08T22:47:14.000Z",
    "sequence": "0",
    "status": "CONFIRMED",
    "summary": "<anonymized - this was a meeting name>",
    "transparency": "OPAQUE",
    "method": "PUBLISH"
}
```

**Comment by devangnegandhi** [comment] 2024-01-15 02:49
Another data point for you to see if this rings any bells - in my google calendar settings, I have set to start my week on sunday. I am not sure if that would cause this issue, but just sharing in case it is helpful

<img width="424" alt="image" src="https://github.com/cloud-atlas-ai/obsidian-ics/assets/812854/ddaa49e2-f5c8-400a-8b85-c81651356bb8">

**Comment by devangnegandhi** [comment] 2024-01-15 19:08
@muness here is a minmal .ics file that has 1 event that I can consistently reproduce this issue with. It only returns an event on Sundays (eg: 2024-01-14), whereas it is supposed to recur on Mondays (eg 2024-01-15)

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Calendar
X-WR-TIMEZONE:America/Los_Angeles
X-WR-CALDESC:For shared events and reminders
BEGIN:VTIMEZONE
TZID:America/Los_Angeles
X-LIC-LOCATION:America/Los_Angeles
BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
TZNAME:PDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
TZNAME:PST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=America/Los_Angeles:20240108T200000
DTEND;TZID=America/Los_Angeles:20240108T210000
RRULE:FREQ=WEEKLY;WKST=SU;UNTIL=20240306T075959Z;BYDAY=MO
EXDATE;TZID=America/Los_Angeles:20240115T200000
DTSTAMP:20240115T020925Z
UID:74tq9lsp6n0qlgln9lph6c3700@google.com
CREATED:20240108T224714Z
DESCRIPTION:Meeting Description
LAST-MODIFIED:20240108T224714Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Meeting Summary
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

**Comment by muness** [comment] 2024-01-21 01:09
> I use google calendar. And its showing it on the wrong day - specifically a day earlier. The event is supposed to be tomorrow evening, but this plugin is showing me that it is taking place today.
> 
> Here is the raw VEVENT event from .ics file
> 
> ```
> BEGIN:VEVENT
> DTSTART;TZID=America/Los_Angeles:20240108T200000
> DTEND;TZID=America/Los_Angeles:20240108T210000
> RRULE:FREQ=WEEKLY;WKST=SU;UNTIL=20240306T075959Z;BYDAY=MO
> EXDATE;TZID=America/Los_Angeles:20240115T200000
> DTSTAMP:20240115T020925Z
> UID:74tq9lsp6n0qlgln9lph6c3700@google.com
> CREATED:20240108T224714Z
> DESCRIPTION:<anonymized description>
> LAST-MODIFIED:20240108T224714Z
> SEQUENCE:0
> STATUS:CONFIRMED
> SUMMARY: <anonymized - this was a meeting name>
> TRANSP:OPAQUE
> END:VEVENT
> ```
> 
> As you can see, FREQ=WEEKLY and WKST=SU and BYDAY=MO. The week should be starting on Sunday, and it should not be showing me this event tomorrow (monday).
> 

Interestingly, for me, in the Eastern timezone this does show up on Mondays.

Let's see what happens when I switch my machine to PT...

**Comment by muness** [comment] 2024-01-21 01:12
> But the cloned event object (from my previous message [above](https://github.com/cloud-atlas-ai/obsidian-ics/issues/98#issuecomment-1891188281)) is suggesting my "wkst" is Saturday (6), and "byweekday" as Sunday (0).
> 
> Could that be the issue?

I don't believe so. From my understanding of the spec and also ran by ChatGPT:

> The WKST=SU part is relevant in rules where the frequency is set to something that involves multiple days of a week (like "biweekly" or "monthly") or when specifying a recurrence like "every second Tuesday." In your case, since the event recurs weekly and is specified to occur on a Monday, the start of the week being Sunday doesn't change the interpretation.

**Comment by muness** [comment] 2024-01-21 01:15
> Let's see what happens when I switch my machine to PT...

When I switch to PT, the event moves to Sunday, as @devangnegandhi is experiencing.

**Comment by dlhawe** [comment] 2024-01-21 01:52
I'm somewhat relieved that I'm not the only one experiencing this issue.  I'm relieved that @devangnegandhi has been able to provide better feedback that I have been on this.

Just an FYI, I am also PT, and I recently had to change my calendar view both in Obsidian and in Google calendar for weeks to start on Mondays because the file.day.weekyear call only uses isoWeeks.  I'll provide feedback on behavior for upcoming reoccuring events.

Thanks again for contuning to chase this down.

**Comment by muness** [comment] 2024-01-21 02:02
This appears to be a symptom of https://github.com/jkbrzt/rrule/issues/452. Specifically:

> It store the date as in UTC time, but when calculating recurrence, it consider[s] the local time,

Ooph...

I'll see if I can apply the [guidance](https://github.com/jkbrzt/rrule?tab=readme-ov-file#timezone-support) in the documentation:

> Whether or not you use the TZID param, make sure to only use JS Date objects that are represented in UTC to avoid unexpected timezone offsets being applied, for example:

**Comment by muness** [comment] 2024-01-21 02:04
> Just an FYI, I am also PT

I don't think I tried switching my own timezone when I tried reproducing the issue previously. That seems to be enough of an offset to trigger the issue in these examples.

Now that I think of it, I have seen the issue in my own calendar, for an all day No Meetings Day event when daylight savings changed.

**Comment by muness** [comment] 2024-01-21 02:56
@devangnegandhi , @dlhawe - please give https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.6.2-rrule-utc-coercion a try.

In my testing, I see a new issue where some events show up on multiple days, but with the correct date. e.g.

```
- [ ] 2024-01-23 17:00 -05:00 - 2024-01-23 17:55 -05:00 meeting name
```

is showing up for me under both the 2024-01-23 _and_ 2024-01-24 journal entries.

---

Let me know if you see other issues. Thanks!

**Comment by muness** [comment] 2024-01-21 02:57
Did I mention lately how much fun timezones are?!

**Comment by devangnegandhi** [comment] 2024-01-23 19:54
@muness This is showing me the event for today correctly

> please give https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.6.2-rrule-utc-coercion a try.

But, I am seeing this issue as well - an event that already happened yesterday is showing up for me today

>In my testing, I see a new issue where some events show up on multiple days, but with the correct date.

**Comment by devangnegandhi** [comment] 2024-01-23 19:58
Let me keep an eye on my events this week, and I will keep you updated on what I see

**Comment by muness** [comment] 2024-01-23 22:00
> @muness This is showing me the event for today correctly
> 
> > please give https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.6.2-rrule-utc-coercion a try.
> 
> But, I am seeing this issue as well - an event that already happened yesterday is showing up for me today
> 
> > In my testing, I see a new issue where some events show up on multiple days, but with the correct date.

Thank you! I think this comes down to the way the timezoned events are matching to non-timezoned matching now. I can add a second filter to make sure they're in the right day. I am trying to think of a better way to match events in the first place. Maybe something like converting everything to UTC first then back. Or maybe I can find another calendar client to see how they address this.

**Comment by muness** [comment] 2024-02-10 17:06
Thanks for the patience @dlhawe , @devangnegandhi , it's been a crazy few weeks at home and work.

I think I figured out a way to address the remaining bug in the fix. Can one of you try https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.6.2-beta2 please? Thanks so much!

**Comment by devangnegandhi** [comment] 2024-02-12 18:47
Hi @muness - unfortunately, this changed has caused a regression. I am seeing a recurring event that is supposed to be tomorrow showing up for me today. Also, a recurring event that is supposed to be today is not there - it shows up if I fetch the events for yesterday.

**Comment by devangnegandhi** [comment] 2024-02-12 18:49
BTW, your previous change was working fine for most of the event - except for some that were showing up for a day later.

**Comment by muness** [comment] 2024-02-12 21:13
> Hi @muness - unfortunately, this changed has caused a regression. I am seeing a recurring event that is supposed to be tomorrow showing up for me today. Also, a recurring event that is supposed to be today is not there - it shows up if I fetch the events for yesterday.

Well, that's unexpected. It sounds like the event itself (in the ics) must be in UTC sometimes, and therefore the last change makes it no match.

I am beginning to wonder if I should just match from the start of the previous day through the next day and then filter events down to just those on the day we're matching. Sigh... I'll put together a test build tonight.

**Comment by muness** [comment] 2024-02-19 22:22
k, one more attempt, with the multi-day UTC check for rrule events then narrowing back down to just today in the current timezone. https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.6.2-beta3

Please let me know if this fixes things, @devangnegandhi

**Comment by muness** [comment] 2024-02-26 00:04
Closing with #113. Please reopen with details if you still see this issue. 🙏

**Closed by muness** 2024-02-26 00:04 UTC
Labels: bug
